on:
  issues:
    types: [opened]
name: Issue Labels
jobs:
  labelIssues:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Apply Issue Labels
      uses: github/issue-labeler@v3.4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler-issue.yml
        enable-versioned-regex: 0
